config/routes.rb
Rails.application.routes.draw do
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees =  Employee.all
    end
    def show
        @employees = Employee.find(params[:id])
    end
    def new
        @employees = Employee.new
    end
    def create
        @employees = Employee.new(employee_params)
        if @employees.save
            redirect_to employees_path
        else
            render :new
        end
    end
    def edit
        @employees = Employee.find(params[:id])
    end
    def update
        @employees = Employee.find(params[:id])
        if @employees.update(employee_params)
          redirect_to employees_path
        else
          render :edit
        end
    end    
    def destroy
        @employees = Employee.find(params[:id])
        @employees.destroy
         redirect_to employees_path 
    end
    private
    def employee_params
        params.require(:employee).permit(:name, :age, :gender,:designation)
    
    end

    GENDER = ["Male", "Female"]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<h1>Edit Here....</h1>
<div align="center">

<h2>Update The Values</h2>
<%= form_for @employees do |f| %>
    <div>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :age %><br>
        <%= f.number_field :age %>
    </div>
    <div>
        <%= f.label :gender %><br>
        <%= f.select(:gender, EmployeesController::GENDER) %>
    </div>
    <div>
        <%= f.label :designation %><br>
        <%= f.text_area :designation %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

</div>

app/views/employees/index.html.erb
<div align="center">
<h1>Employee list</h1>
<%= link_to "Create An Employee", new_employee_path %>
<table border=1>
 <thead>
   <th>Name</th>
   <th>Age</th>
   <th>Gender</th>
   <th>Designation</th>
 </thead>
 <% @employees.each do |employee| %>
 <tr>
   <td><%= employee.name %></td>
   <td><%= employee.age %></td>
   <td><%= employee.gender %></td>
   <td><%= employee.designation %></td>
   <td>
     <%= link_to "Edit", edit_employee_path(employee) %>
     <%= link_to "Delete", employee, method: :delete,data: { confirm: "Sure to delete?"} %>
   </td>
 </tr>
  <% end %>
</table>
</div>

app/views/employees/new.html.erb
<h1>Create Here....</h1>
<div align="center">

<h2>Enter The Details</h2>
<%= form_for @employees do |f| %>
    <div>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :age %><br>
        <%= f.number_field :age %>
    </div>
    <div>
        <%= f.label :gender %><br>
        <%= f.select(:gender, EmployeesController::GENDER) %>
    </div>
    <div>
        <%= f.label :designation %><br>
        <%= f.text_area :designation %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>